import Head from "next/head"
import SixxabNav, { SixxabMark, SixxabWordmark } from "../components/SixxabNav"

const N = "#0A0E1A", AMBER = "#EF9F27"

const SECTIONS = [
  { title:"1. Acceptance of terms",
    body:`By accessing or using SIXXAB AI ("the Service") at startupsinabox.com, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. These terms apply to all users including visitors, customers and contributors.` },
  { title:"2. Description of service",
    body:`SIXXAB AI is an autonomous business platform providing AI-powered tools including the Founder Enterprise Orchestrator, CXO Suite, SIXXAB CRM, Niche Selector, Vertical Agent Packs, and associated services. The platform is offered on a subscription basis.` },
  { title:"3. Subscription and payment",
    body:`Subscriptions are billed monthly or annually through Stripe. Founding member rates are locked at the time of first payment. You may cancel at any time; access continues until the end of the paid period. No refunds are issued for partial months except where required by law. We offer a 14-day money-back guarantee for first-time subscribers.` },
  { title:"4. Acceptable use",
    body:`You agree not to use SIXXAB AI to: (a) violate any applicable law; (b) send unsolicited communications (spam); (c) reverse-engineer the platform; (d) share account credentials; (e) use the service to build a competing product. We reserve the right to suspend accounts that violate these terms without refund.` },
  { title:"5. AI-generated content",
    body:`SIXXAB AI uses large language models to generate content, scripts, plans and recommendations. All AI-generated output is provided for informational and operational purposes only. SIXXAB AI makes no warranty regarding the accuracy, completeness, or fitness for purpose of AI-generated content. You are responsible for reviewing and approving all content before use.` },
  { title:"6. Data and privacy",
    body:`Your use of the Service is also governed by our Privacy Policy. We collect the minimum data necessary to provide the Service. Contact data entered into SIXXAB CRM is stored in your browser's local storage and is not transmitted to our servers unless explicitly sent via email or agent functions. We do not sell your data.` },
  { title:"7. Intellectual property",
    body:`SIXXAB AI, its branding, design, orchestrator framework and vertical agent packs are the intellectual property of SIXXAB AI (startupsinabox.com). You retain all rights to content you create using the Service. Content generated by the AI is provided to you without restriction for your business use.` },
  { title:"8. Limitation of liability",
    body:`To the maximum extent permitted by law, SIXXAB AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including lost profits, revenue or data, arising from your use of the Service. Our total liability shall not exceed the amount you paid in the 12 months preceding the claim.` },
  { title:"9. Termination",
    body:`We may suspend or terminate your access to the Service at any time for violation of these terms. You may terminate your subscription at any time through your account settings. Upon termination, your right to use the Service ceases immediately.` },
  { title:"10. Governing law",
    body:`These terms are governed by the laws of the State of Texas, United States. Any disputes shall be resolved in the courts of Dallas County, Texas, or through binding arbitration at our election.` },
  { title:"11. Changes to terms",
    body:`We may update these terms from time to time. We will notify subscribers of material changes by email. Continued use of the Service after changes constitutes acceptance of the updated terms.` },
  { title:"12. Contact",
    body:`For questions about these terms, contact us at sunil.kattikar@gmail.com or through the contact page at startupsinabox.com/contact.` },
]

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service · SIXXAB AI</title>
        <meta name="description" content="SIXXAB AI Terms of Service — autonomous business platform usage terms."/>
      </Head>
      <SixxabNav active=""/>
      <div style={{ maxWidth:760, margin:"0 auto", padding:"48px 5% 80px" }}>
        <div style={{ marginBottom:36 }}>
          <div style={{ fontFamily:"'DM Mono',monospace", fontSize:10.5, color:AMBER,
                        letterSpacing:".12em", textTransform:"uppercase", marginBottom:10 }}>
            Legal · Last updated June 2025
          </div>
          <h1 style={{ fontFamily:"Georgia,serif", fontSize:36, fontWeight:700,
                        color:N, marginBottom:12, lineHeight:1.15 }}>
            Terms of Service
          </h1>
          <p style={{ fontSize:15, color:"#64748B", lineHeight:1.75 }}>
            Please read these terms carefully before using SIXXAB AI — Autonomous Business Platform.
          </p>
        </div>
        {SECTIONS.map((s,i) => (
          <div key={i} style={{ marginBottom:28, paddingBottom:28,
                                 borderBottom: i < SECTIONS.length-1 ? "1px solid #E8ECF4" : "none" }}>
            <h2 style={{ fontFamily:"Georgia,serif", fontSize:17, fontWeight:700,
                          color:N, marginBottom:10 }}>{s.title}</h2>
            <p style={{ fontSize:14.5, color:"#475569", lineHeight:1.8 }}>{s.body}</p>
          </div>
        ))}
        <div style={{ marginTop:40, padding:"20px 24px", background:"#F8F9FA",
                      borderRadius:12, border:"1px solid #E2E8F0" }}>
          <p style={{ fontSize:14, color:"#64748B", lineHeight:1.7 }}>
            <strong style={{ color:N }}>Questions?</strong> Email us at{" "}
            <a href="mailto:sunil.kattikar@gmail.com"
               style={{ color:AMBER, textDecoration:"none", fontWeight:500 }}>
              sunil.kattikar@gmail.com
            </a>{" "}
            or{" "}
            <a href="/contact" style={{ color:AMBER, textDecoration:"none", fontWeight:500 }}>
              use our contact form
            </a>.
          </p>
        </div>
      </div>
    </>
  )
}
